### ISSUE TITLE
Add support for sendMessageReturnHash

### ISSUE THREAD

**Issue by akme** [tonkeeper/tongo#139]
It would be great to have [raw.sendMessageReturnHash](https://github.com/ton-blockchain/ton/blob/master/tl/generate/scheme/tonlib_api.tl#LL265C59-L265C59) implemented in addition to raw.sendMessage.
My idea is that it would bring more info for tx flow, like getting something similar to txid on send, so we can generate a link for different explorers.

**Comment by mr-tron** [comment]
wallet.SendV2 and wallet.RawSendV2
