### ISSUE TITLE
Hello, I can not get the amount in my Account through this, the return is Account status: nonexist Balance: 0  But I am sure there is money in my account

### ISSUE THREAD

**Issue by MaGua-Bishop** [tonkeeper/tongo#149]
`package main

import (
	"context"
	"fmt"
	"github.com/tonkeeper/tongo"
	"github.com/tonkeeper/tongo/liteapi"
)

func main() {
	// options, err := config.ParseConfigFile("path/to/config.json")
	tongoClient, err := liteapi.NewClientWithDefaultTestnet()
	if err != nil {
		fmt.Printf("Unable to create tongo client: %v", err)
	}
	accountId := tongo.MustParseAccountID("EQBv0pu1P2aKw48WArnzg3YwhQ8NsExGKm_931At-iWGbsUA")
	state, err := tongoClient.GetAccountState(context.Background(), accountId)
	if err != nil {
		fmt.Printf("Get account state error: %v", err)
	}
	acc, _ := tongo.GetAccountInfo(state.Account)
	fmt.Printf("Account status: %v\nBalance: %v\n", acc.Status, acc.Balance)
}
`
And can you tell me how to get the private key through the short word？

**Comment by aleksej-paschenko** [comment]
To get a private key from a seed phrase, you can use `wallet.SeedToPrivateKey` function

https://github.com/tonkeeper/tongo/blob/master/wallet/seed.go#L29

**Comment by MaGua-Bishop** [comment]
Hello, I used this code as prompted, but the return is not quite right

`package main

import (
	"fmt"
	"github.com/tonkeeper/tongo/wallet"
)

func main() {
	address, _ := wallet.SeedToPrivateKey("labor catalog adjust whale cliff earn false there build.........")
	fmt.Println(address)
}
`

output:
[]

**Comment by mr-tron** [comment]
`wallet.SeedToPrivateKey` returns not an address but just private key. you can convert it to address with `wallet.New(privateKey, over agrs).GetAddress()`
but for your case i think you should not to skip error check. probably you use not compatible with TON seed phrase (seed phrase for TON has different checksum algorithm)
