### ISSUE TITLE
SendV2 return tx hash can not query by /v2/blockchain/transactions/

### ISSUE THREAD

**Issue by yangyile1990** [tonkeeper/tongo#183]
func (w *Wallet) SendV2(
	ctx context.Context,
	waitingConfirmation time.Duration,
	messages ...Sendable,
) (ton.Bits256, error)

after exec this I get a hash da5886713fe53229dd4f8ceced7ec62890f2c1c6629bf74085bd4e1a8c8e0b95

while the hash is not tx hash. (can not search by /v2/blockchain/transactions/)

but is bb4f07ec147756fe3c1ef57d7397f6f19e4cd12869be0e96940a6f91c703bed4

https://testnet.tonviewer.com/transaction/da5886713fe53229dd4f8ceced7ec62890f2c1c6629bf74085bd4e1a8c8e0b95

why?

how to use da5886713fe53229dd4f8ceced7ec62890f2c1c6629bf74085bd4e1a8c8e0b95 get bb4f07ec147756fe3c1ef57d7397f6f19e4cd12869be0e96940a6f91c703bed4

**Comment by aleksej-paschenko** [comment]
`SendV2` returns a hash of your [message](https://github.com/ton-blockchain/ton/blob/master/crypto/block/block.tlb#L155-L163) because it is not possible to know a transaction hash at this point. 

There is no guarantee that your message is unique in general BUT that works for wallet contracts because of seqno stored in msg.Body.

**Comment by yangyile1990** [comment]
OK, but how does the 
```
https://testnet.tonviewer.com/transaction/8e3264cf6e4c793e4cf2f189aa8b9aed735c3af5faefd1f7730a628f80e61274
```
can work.

<img width="1179" alt="截屏2023-09-27 17 28 39" src="https://github.com/tonkeeper/tongo/assets/56903488/a4fe95a7-3f55-4862-9fe3-0055c6d9bf85">

you can see the image.

the 8e3264cf6e4c793e4cf2f189aa8b9aed735c3af5faefd1f7730a628f80e61274 is the result of SendV2.

and the fc5833bfacfce678905eb29bdeafa1c8d7c75ae2fb286c6691d9d7a663dc75a8 is find as hash.

How does it work.

is there any other sdk or api to get(8e3264cf6e4c793e4cf2f189aa8b9aed735c3af5faefd1f7730a628f80e61274) return fc5833bfacfce678905eb29bdeafa1c8d7c75ae2fb286c6691d9d7a663dc75a8?

**Comment by mr-tron** [comment]
I don't know any over services but any index can implement it. I hope in the future over indexes also will support it.
