### ISSUE TITLE
Hello, I would like to know how to query transactions through message hash, as I couldn't find it in the code.

### ISSUE THREAD

**Issue by vingin007** [tonkeeper/tongo#205]

**Comment by aleksej-paschenko** [comment]
Not sure that I got your question. 
Can you explain your use case? are you trying to find a transaction in a block by msg hash?

**Comment by yangyile1990** [comment]
"github.com/tonkeeper/tonapi-go"

GetBlockchainTransactionByMessageHash

This can get one hash.

then:
https://testnet.tonapi.io/v2/blockchain/messages/b0d50cba04aa176523d7314f14d61e89f2c42c74e19889743e9be31e66032a66/transaction

https://testnet.tonapi.io/v2/blockchain/transactions/8bbb1d9b8ebe77d57792d13e35f36a361d633735e948aa170e1fa804cbdbccb5
request result are same.

**Comment by mr-tron** [comment]
Ok. This is example how you can find transaction by message hash. And what is your question?

**Comment by Amirsadeqi20** [comment]
چگونه دست رسی به توکن های بلاک شده
