### ISSUE TITLE
How the get the relative transactions?

### ISSUE THREAD

**Issue by yangyile1990** [tonkeeper/tongo#228]
hello sir. I use the 
https://testnet.tonviewer.com/transaction/77fb3cc4ad47a5d9dcd178f91d5454eee42e14c267056375975f227e6df78d92
or the 
https://testnet.tonviewer.com/transaction/4c53b8e11851672876e354f537d4ae9d16cf3f9e9f7c3bd47ca2b1fbc8fba0db
can get almost same result.

what is the logic of this page?

if I only have  77fb3cc4ad47a5d9dcd178f91d5454eee42e14c267056375975f227e6df78d92 how can I get the 4c53b8e11851672876e354f537d4ae9d16cf3f9e9f7c3bd47ca2b1fbc8fba0db

or If I only have 4c53b8e11851672876e354f537d4ae9d16cf3f9e9f7c3bd47ca2b1fbc8fba0db  how can I get 77fb3cc4ad47a5d9dcd178f91d5454eee42e14c267056375975f227e6df78d92

the tonviewer is the tonviewer. 

but I want to use the api to get the result. not see by eyes.

which api can I use?

this api is not ok:
https://testnet.toncenter.com/api/v2/getBlockTransactions?workchain=0&shard=8000000000000000&seqno=17229018&root_hash=77fb3cc4ad47a5d9dcd178f91d5454eee42e14c267056375975f227e6df78d92&count=40
because it give me 4 results. while I need is 2.
so please help me.

**Comment by mr-tron** [comment]
https://tonapi.io/v2/traces/{hash}
