### ISSUE TITLE
How to send a contract transaction?

### ISSUE THREAD

**Issue by 6xiaowu9** [tonkeeper/tongo#277]
How to send a contract transaction?

We need a demo, thanks!

**Comment by Tuppo91** [comment]
> How to send a contract transaction?
> 
> We need a demo, thanks!

**Comment by Tuppo91** [comment]
https://github.com/tonkeeper/tongo/issues/277#issue-2415926335

**Comment by mr-tron** [comment]
did you check `example` directory? 
https://github.com/tonkeeper/tongo/blob/master/examples/wallet/simple_send/main.go
